version: 2
updates:
- package-ecosystem: npm
  directory: "/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - JonathanTreffler
  ignore:
  - dependency-name: mathlive
    versions:
    - 0.60.0
    - 0.60.1
    - 0.61.0
  - dependency-name: eslint
    versions:
    - 7.22.0
- package-ecosystem: npm
  directory: "/dev-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - JonathanTreffler
