tasks:
  - init: linking core to dev-server and starting dev server
    command: cd core && npm link && cd ../dev-server/ && npm install && npm link
      @fractava/fractava-notes-core && npm run serve
